/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "SCLK_3_aliases.h"
#include "SCLK_3.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "SPIM_2.h"
#include "SPIM_2_PVT.h"
#include "MOSI_3_aliases.h"
#include "MOSI_3.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "SS_2_aliases.h"
#include "SS_2.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "SCLK_2_aliases.h"
#include "SCLK_2.h"
#include "SS_3_aliases.h"
#include "SS_3.h"
#include "LED_aliases.h"
#include "LED.h"
#include "MISO_2_aliases.h"
#include "MISO_2.h"
#include "MOSI_2_aliases.h"
#include "MOSI_2.h"
#include "SPIM_3.h"
#include "SPIM_3_PVT.h"
#include "MISO_3_aliases.h"
#include "MISO_3.h"
#include "CapSense_CompCH0.h"
#include "CapSense_IdacCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IntClock.h"
#include "SPIM_2_IntClock.h"
#include "SPIM_1_IntClock.h"
#include "SPIM_3_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

