/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloader.h"
#include "Bootloader_PVT.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "LED3_aliases.h"
#include "LED3.h"
#include "LED4_aliases.h"
#include "LED4.h"
#include "GreenLED_aliases.h"
#include "GreenLED.h"
#include "RedLED_aliases.h"
#include "RedLED.h"
#include "RedLED2_aliases.h"
#include "RedLED2.h"
#include "GreenLED2_aliases.h"
#include "GreenLED2.h"
#include "SPIM_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

